services:

    postgres:
        restart: always
        image: postgres:15
        container_name: rsd_db
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - rsd_network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
            interval: 5s
            timeout: 5s
            retries: 5
    backend:
        build: ./backend
        command: >
            sh -c "cd app/alembic && alembic upgrade head &&
                cd .. && cd .. &&
                python server.py"
        container_name: rsd_backend
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            SECRET_KEY: ${SECRET_KEY}
            ALGORITHM: ${ALGORITHM}
        ports:
            - '8000:8000'
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - rsd_network
        volumes:
            - ./backend:/backend
            - /app/__pycache__
    bot:
        build: ./bot
        container_name: rsd_bot
        restart: always
        depends_on:
            - db
            - qdrant

        environment:
            NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
            ENCRYPTION_KEY: ${ENCRYPTION_KEY}
            QDRANT_URL: ${QDRANT_URL}
            DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
            DB_NAME: ${DB_NAME}
            MASTER_BOT_TOKEN: ${MASTER_BOT_TOKEN}
            BASE_URL: ${BASE_URL}
            API_HOST: ${API_HOST}
            API_PORT: ${API_PORT}
        ports:
            - "8001:8001"
        networks:
            - rsd_network
        volumes:
            - ./bot:/app
            - ./temp_uploads:/app/temp_uploads
    qdrant:
        image: qdrant/qdrant:latest
        container_name: rsd_qdrant
        restart: always
        ports:
            - "6333:6333"
            - "6334:6334"
        volumes:
            - qdrant_data:/qdrant/storage
        networks:
            - rsd_network
    ngrok:
        image: ngrok/ngrok:latest
        restart: always
        command:
            - "http"
            - "app:8001"
        environment:
        NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
        depends_on:
            - app

networks:
  rsd_network:
    driver: bridge

volumes:
    postgres_data:
    qdrant_data:
