"""agents & documents

Revision ID: 399a6834dc1d
Revises: 2034922d52f9
Create Date: 2026-03-10 17:56:56.424884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '399a6834dc1d'
down_revision: Union[str, Sequence[str], None] = '2034922d52f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bot_username', sa.String(length=100), nullable=True),
    sa.Column('encrypted_token', sa.String(length=500), nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('registered', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id'),
    sa.UniqueConstraint('encrypted_token')
    )
    op.create_table('agentdocuments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('subscription_type', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('subscription_end_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('telegram_id', sa.BigInteger(), nullable=False))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.alter_column('users', 'name',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('users', 'telegram_id')
    op.drop_column('users', 'subscription_end_date')
    op.drop_column('users', 'subscription_type')
    op.drop_table('agentdocuments')
    op.drop_table('agents')
    # ### end Alembic commands ###
