"""add_projects_table

Revision ID: a2b3c4d5e6f7
Revises: d3e4f5a6b7c8
Create Date: 2026-06-30 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2b3c4d5e6f7'
down_revision = 'd3e4f5a6b7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create projects table
    op.create_table(
        'projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('slug', sa.String(length=80), nullable=False),
        sa.Column('industry', sa.String(length=64), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('brief_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
        sa.Column('ai_plan_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
        sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
        sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'slug', name='uq_project_user_slug')
    )
    
    # Create indexes
    op.create_index('ix_projects_user_id_status', 'projects', ['user_id', 'status'])
    op.create_index('ix_projects_is_default', 'projects', ['user_id', 'is_default'])
    op.create_index('ix_projects_slug', 'projects', ['slug'])
    
    # Add project_id to agents table
    op.add_column('agents', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_agents_project_id', 'agents', 'projects',
        ['project_id'], ['id'], ondelete='SET NULL'
    )
    op.create_index('ix_agents_project_id', 'agents', ['project_id'])
    
    # Add project_id to websites table
    op.add_column('websites', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_websites_project_id', 'websites', 'projects',
        ['project_id'], ['id'], ondelete='SET NULL'
    )
    op.create_index('ix_website_project', 'websites', ['project_id'])
    
    # ### end Alembic commands ###
    
    # Data migration: create default project for each user with agents or websites
    op.execute("""
        INSERT INTO projects (user_id, name, slug, industry, description, status, is_default, created_at, updated_at)
        SELECT 
            u.id,
            'Мой бизнес',
            'my-business-' || u.id,
            NULL,
            'Автоматически созданный проект',
            'active',
            true,
            NOW(),
            NOW()
        FROM users u
        WHERE NOT EXISTS (
            SELECT 1 FROM projects p WHERE p.user_id = u.id AND p.is_default = true
        )
    """)
    
    # Link existing agents to default projects
    op.execute("""
        UPDATE agents a
        SET project_id = p.id
        FROM projects p
        WHERE a.user_id = p.user_id 
        AND p.is_default = true
        AND a.project_id IS NULL
    """)
    
    # Link existing websites to default projects
    op.execute("""
        UPDATE websites w
        SET project_id = p.id
        FROM projects p
        WHERE w.owner_id = p.user_id 
        AND p.is_default = true
        AND w.project_id IS NULL
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove project_id from websites
    op.drop_index('ix_website_project', table_name='websites')
    op.drop_constraint('fk_websites_project_id', 'websites', type_='foreignkey')
    op.drop_column('websites', 'project_id')
    
    # Remove project_id from agents
    op.drop_index('ix_agents_project_id', table_name='agents')
    op.drop_constraint('fk_agents_project_id', 'agents', type_='foreignkey')
    op.drop_column('agents', 'project_id')
    
    # Drop projects table
    op.drop_index('ix_projects_slug', table_name='projects')
    op.drop_index('ix_projects_is_default', table_name='projects')
    op.drop_index('ix_projects_user_id_status', table_name='projects')
    op.drop_table('projects')
    
    # ### end Alembic commands ###
