"""add_project_documents

Revision ID: b3c4d5e6f7g8
Revises: a2b3c4d5e6f7
Create Date: 2026-06-30 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3c4d5e6f7g8'
down_revision = 'a2b3c4d5e6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create project_documents table
    op.create_table(
        'project_documents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('file_name', sa.String(length=255), nullable=False),
        sa.Column('content_hash', sa.String(length=64), nullable=True),
        sa.Column('embedding_profile_key', sa.String(length=64), server_default='bge_m3_v1', nullable=False),
        sa.Column('embedding_schema_version', sa.Integer(), server_default='1', nullable=False),
        sa.Column('embedding_model_name', sa.String(length=128), server_default='BAAI/bge-m3', nullable=False),
        sa.Column('chunk_size', sa.Integer(), server_default='1000', nullable=False),
        sa.Column('chunk_overlap', sa.Integer(), server_default='100', nullable=False),
        sa.Column('status', sa.String(length=15), server_default='processing', nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes
    op.create_index('ix_project_documents_project_id', 'project_documents', ['project_id'])
    op.create_index('ix_project_documents_content_hash', 'project_documents', ['content_hash'])
    op.create_index('ix_project_documents_status', 'project_documents', ['status'])
    op.create_index('ix_project_documents_project_status', 'project_documents', ['project_id', 'status'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index('ix_project_documents_project_status', table_name='project_documents')
    op.drop_index('ix_project_documents_status', table_name='project_documents')
    op.drop_index('ix_project_documents_content_hash', table_name='project_documents')
    op.drop_index('ix_project_documents_project_id', table_name='project_documents')
    op.drop_table('project_documents')
    
    # ### end Alembic commands ###
