"""add_website_builder_tables

Revision ID: t1u2v3w4x5y6
Revises: s9t0u1v2w3x4
Create Date: 2026-06-01 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 't1u2v3w4x5y6'
down_revision: Union[str, None] = 's9t0u1v2w3x4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Website Templates table
    op.create_table(
        'website_templates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('description', sa.String(length=512), nullable=True),
        sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
        sa.Column('default_blocks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column('default_styles', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name', name='uq_website_template_name')
    )
    op.create_index('ix_website_templates_name', 'website_templates', ['name'], unique=True)
    op.create_index('ix_website_templates_created_at', 'website_templates', ['created_at'], unique=False)

    # Websites table
    op.create_table(
        'websites',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('agent_id', sa.Integer(), nullable=True),
        sa.Column('template_id', sa.Integer(), nullable=True),
        sa.Column('slug', sa.String(length=50), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=True),
        sa.Column('meta_description', sa.String(length=500), nullable=True),
        sa.Column('og_title', sa.String(length=100), nullable=True),
        sa.Column('og_description', sa.String(length=300), nullable=True),
        sa.Column('og_image_url', sa.String(length=1024), nullable=True),
        sa.Column('favicon_url', sa.String(length=1024), nullable=True),
        sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
        sa.Column('generation_status', sa.String(length=16), server_default='idle', nullable=True),
        sa.Column('custom_styles', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('published_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['template_id'], ['website_templates.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug', name='uq_website_slug')
    )
    op.create_index('ix_websites_slug', 'websites', ['slug'], unique=True)
    op.create_index('ix_websites_owner_status', 'websites', ['owner_id', 'status'], unique=False)
    op.create_index('ix_websites_agent', 'websites', ['agent_id'], unique=False)
    op.create_index('ix_websites_created_at', 'websites', ['created_at'], unique=False)
    op.create_index('ix_websites_status', 'websites', ['status'], unique=False)

    # Website Blocks table
    op.create_table(
        'website_blocks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('website_id', sa.Integer(), nullable=False),
        sa.Column('order', sa.Integer(), server_default='0', nullable=False),
        sa.Column('type', sa.String(length=32), nullable=False),
        sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column('styles', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_website_blocks_website_id', 'website_blocks', ['website_id'], unique=False)
    op.create_index('ix_website_blocks_type', 'website_blocks', ['type'], unique=False)
    op.create_index('ix_website_block_website_order', 'website_blocks', ['website_id', 'order'], unique=False)

    # Website Domains table
    op.create_table(
        'website_domains',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('website_id', sa.Integer(), nullable=False),
        sa.Column('domain', sa.String(length=253), nullable=False),
        sa.Column('ssl_enabled', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('verification_status', sa.String(length=16), server_default='pending', nullable=False),
        sa.Column('verification_token', sa.String(length=64), nullable=True),
        sa.Column('verified_at', sa.DateTime(), nullable=True),
        sa.Column('last_dns_check_at', sa.DateTime(), nullable=True),
        sa.Column('dns_check_error', sa.String(length=512), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('domain', name='uq_website_domain')
    )
    op.create_index('ix_website_domains_domain', 'website_domains', ['domain'], unique=True)
    op.create_index('ix_website_domains_website', 'website_domains', ['website_id'], unique=False)
    op.create_index('ix_website_domains_created_at', 'website_domains', ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_website_domains_created_at', table_name='website_domains')
    op.drop_index('ix_website_domains_website', table_name='website_domains')
    op.drop_index('ix_website_domains_domain', table_name='website_domains')
    op.drop_table('website_domains')

    op.drop_index('ix_website_block_website_order', table_name='website_blocks')
    op.drop_index('ix_website_blocks_type', table_name='website_blocks')
    op.drop_index('ix_website_blocks_website_id', table_name='website_blocks')
    op.drop_table('website_blocks')

    op.drop_index('ix_websites_status', table_name='websites')
    op.drop_index('ix_websites_created_at', table_name='websites')
    op.drop_index('ix_websites_agent', table_name='websites')
    op.drop_index('ix_websites_owner_status', table_name='websites')
    op.drop_index('ix_websites_slug', table_name='websites')
    op.drop_table('websites')

    op.drop_index('ix_website_templates_created_at', table_name='website_templates')
    op.drop_index('ix_website_templates_name', table_name='website_templates')
    op.drop_table('website_templates')
    # ### end Alembic commands ###
