/**
 * Application constants
 * Defines static values used throughout the application
 */

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};

export const API_ROUTES = {
  // Auth (backend: prefix /api/users)
  AUTH_LOGIN: '/api/users/login',
  AUTH_GOOGLE: '/api/users/oauth/google',
  AUTH_REGISTER: '/api/users/registration',
  AUTH_REGISTER_RESEND_CODE: '/api/users/registration/resend-code',
  AUTH_REGISTER_VERIFY: '/api/users/registration/verify',
  AUTH_PASSWORD_RESET_REQUEST: '/api/users/password-reset/request',
  AUTH_PASSWORD_RESET_VERIFY: '/api/users/password-reset/verify',
  AUTH_PASSWORD_RESET_CONFIRM: '/api/users/password-reset/confirm',
  AUTH_LOGOUT: '/api/users/logout',
  AUTH_REFRESH: '/api/users/refresh',

  // Partner referrals
  REFERRALS_PARTNER_DASHBOARD: '/api/referrals/partner/dashboard',
  REFERRALS_PARTNER_PROMO_CODES: '/api/referrals/partner/promo-codes',
  REFERRALS_PARTNER_PROMO_CODE: (promoCodeId) => `/api/referrals/partner/promo-codes/${promoCodeId}`,
  REFERRALS_PARTNER_PAYOUT_BALANCE: '/api/referrals/partner/payouts/balance',
  REFERRALS_PARTNER_PAYOUTS: '/api/referrals/partner/payouts',

  // Users
  USERS_ME: '/api/users/me',
  USERS_PROFILE: '/api/users/profile',
  USERS_TELEGRAM_LINK_START: '/api/users/telegram-link/start',
  USER_ERROR_REPORTS: '/api/users/error-reports',

  // Agents
  AGENTS_LIST: '/api/agents/allBy_tgID',
  AGENTS_CREATE_EMPTY: '/api/agents',
  AGENTS_CREATE: '/api/agents/by_token',
  AGENTS_CREATE_USERBOT: '/api/agents/by_userbot_session',
  AGENTS_USERBOT_REQUEST_CODE: '/api/agents/userbot/request_code',
  AGENTS_USERBOT_VERIFY_CODE: '/api/agents/userbot/verify_code',
  AGENTS_USERBOT_QR_START: '/api/agents/userbot/qr/start',
  AGENTS_USERBOT_QR_STATUS: '/api/agents/userbot/qr/status',
  AGENTS_USERBOT_QR_VERIFY_2FA: '/api/agents/userbot/qr/verify_2fa',
  AGENTS_USERBOT_IMPORT_SESSION: '/api/agents/userbot/import_session',
  AGENTS_MAX_USERBOT_REQUEST_CODE: '/api/agents/max_userbot/request_code',
  AGENTS_MAX_USERBOT_VERIFY_CODE: '/api/agents/max_userbot/verify_code',
  AGENTS_MAX_USERBOT_QR_START: '/api/agents/max_userbot/qr/start',
  AGENTS_MAX_USERBOT_QR_STATUS: '/api/agents/max_userbot/qr/status',
  AGENTS_MAX_USERBOT_QR_VERIFY_2FA: '/api/agents/max_userbot/qr/verify_2fa',
  AGENTS_MAX_USERBOT_IMPORT_SESSION: '/api/agents/max_userbot/import_session',
  AGENTS_WHATSAPP_USERBOT_REQUEST_CODE: '/api/agents/whatsapp_userbot/request_code',
  AGENTS_WHATSAPP_USERBOT_VERIFY_CODE: '/api/agents/whatsapp_userbot/verify_code',
  AGENTS_WHATSAPP_USERBOT_AUTH_STATUS: '/api/agents/whatsapp_userbot/auth_status',
  AGENTS_CHANNELS_LIST: '/api/agents/channels',
  AGENTS_CHANNELS_ADD_BOT: '/api/agents/channels/by_token',
  AGENTS_CHANNELS_ADD_USERBOT: '/api/agents/channels/by_userbot_session',
  AGENTS_CHANNELS_ADD_MAX_BOT: '/api/agents/channels/by_max_bot',
  AGENTS_CHANNELS_ADD_MAX_USERBOT: '/api/agents/channels/by_max_userbot',
  AGENTS_CHANNELS_ADD_WHATSAPP_USERBOT: '/api/agents/channels/by_whatsapp_userbot',
  AGENTS_CHANNELS_ADD_WHATSAPP_BUSINESS_API: '/api/agents/channels/by_whatsapp_business_api',
  AGENTS_CHANNELS_ADD_TELEPHONY: '/api/agents/channels/add-telephony',
  AGENTS_CHANNELS_VALIDATE_TELEPHONY: '/api/agents/channels/telephony/validate',
  AGENTS_CHANNELS_TELEPHONY_PLATFORM: '/api/agents/channels/telephony/platform',
  AGENTS_CHANNELS_DELETE: '/api/agents/channels',
  AGENTS_ANALYTICS_TELEPHONY_CALLS: '/api/agents/analytics/telephony/calls',
  AGENTS_UPDATE: '/api/agents/by_botID',
  AGENTS_DELETE: '/api/agents',
  AGENTS_DETAIL: '/api/agents',
  AGENTS_TOGGLE: '/api/agents/toggle_status',
  AGENTS_AUTOPAY: '/api/agents/autopay',
  AGENTS_AI_IMPROVE_PROMPT: '/api/agents/ai/improve_prompt',
  AGENTS_AI_GENERATE_WELCOME: '/api/agents/ai/generate_welcome',
  AGENTS_AI_GENERATE_DRAFT: '/api/agents/ai/generate-draft',
  AGENTS_EXTERNAL_CHAT: '/api/agents/external/chat',
  AGENTS_REGENERATE_EXTERNAL_KEY: '/api/agents/external/regenerate_key',
  AGENTS_ANALYTICS_SUMMARY: '/api/agents/analytics/summary',
  AGENTS_ANALYTICS_CHATS: '/api/agents/analytics/chats',
  AGENTS_ANALYTICS_TIMESERIES: '/api/agents/analytics/timeseries',
  AGENTS_ANALYTICS_CRM_ACTIONS: '/api/agents/analytics/crm_actions',
  AGENTS_ANALYTICS_FROZEN: '/api/agents/analytics/frozen',
  AGENTS_TELEGRAM_SEND_TO_USER: '/api/agents/telegram/send_to_user',
  AGENTS_EXTERNAL_SEND_TO_USER: '/api/agents/external/send_to_user',
  AGENTS_TELEGRAM_BROADCAST_RECIPIENTS: '/api/agents/telegram/broadcast_recipients',
  AGENTS_TELEGRAM_BROADCAST: '/api/agents/telegram/broadcast',
  AGENTS_WHATSAPP_USERBOT_SEND_TO_USER: '/api/agents/whatsapp_userbot/send_to_user',
  AGENTS_MAX_USERBOT_SEND_TO_USER: '/api/agents/max_userbot/send_to_user',
  AGENTS_WHATSAPP_USERBOT_BROADCAST_RECIPIENTS: '/api/agents/whatsapp_userbot/broadcast_recipients',
  AGENTS_WHATSAPP_USERBOT_BROADCAST: '/api/agents/whatsapp_userbot/broadcast',
  AGENTS_SALES_MANAGER_EXCEL_UPLOAD: '/api/agents/sales_manager/contacts/excel-upload',
  AGENTS_SALES_MANAGER_IMPORT_STATUS: '/api/agents/sales_manager/contacts/import-status',
  AGENTS_CRM_CONNECT: '/api/agents/crm/connect',
  AGENTS_CRM_VALIDATE: '/api/agents/crm/validate',
  AGENTS_CRM_HEALTH: '/api/agents/crm/health',
  AGENTS_ADMIN_TEMPLATE_STAFF: '/api/agents/admin_template/staff',
  AGENTS_ADMIN_TEMPLATE_SERVICES: '/api/agents/admin_template/services',
  AGENTS_ADMIN_TEMPLATE_RESOURCES: '/api/agents/admin_template/resources',
  AGENTS_ADMIN_TEMPLATE_SCHEDULE: '/api/agents/admin_template/schedule',
  AGENTS_ADMIN_TEMPLATE_SCHEDULE_AVAILABLE: '/api/agents/admin_template/schedule/available',
  AGENTS_ADMIN_TEMPLATE_APPOINTMENTS: '/api/agents/admin_template/appointments',
  AGENTS_ADMIN_TEMPLATE_APPOINTMENTS_RESCHEDULE: '/api/agents/admin_template/appointments/reschedule',
  AGENTS_ADMIN_TEMPLATE_APPOINTMENTS_CANCEL: '/api/agents/admin_template/appointments/cancel',
  AGENTS_ADMIN_TEMPLATE_APPOINTMENTS_CONFIRM: '/api/agents/admin_template/appointments/confirm',
  AGENTS_ADMIN_TEMPLATE_REFUND_REQUESTS: '/api/agents/admin_template/refund_requests',
  AGENTS_ADMIN_TEMPLATE_REFUND_REQUESTS_APPROVE: '/api/agents/admin_template/refund_requests/approve',
  AGENTS_ADMIN_TEMPLATE_REFUND_REQUESTS_REJECT: '/api/agents/admin_template/refund_requests/reject',
  AGENTS_ADMIN_TEMPLATE_OCCUPANCY: '/api/agents/admin_template/occupancy',
  AGENTS_ADMIN_TEMPLATE_WAITLIST: '/api/agents/admin_template/waitlist',
  AGENTS_ADMIN_TEMPLATE_CLIENT_PROFILES: '/api/agents/admin_template/client_profiles',
  AGENTS_ADMIN_TEMPLATE_QUICK_REPLIES: '/api/agents/admin_template/quick_replies',
  AGENTS_ADMIN_TEMPLATE_REMINDERS_RUN: '/api/agents/admin_template/reminders/run',
  AGENTS_ADMIN_TEMPLATE_APPLICATIONS: '/api/agents/admin_template/applications',
  AGENTS_ADMIN_TEMPLATE_APPLICATIONS_STATS: '/api/agents/admin_template/applications/stats',
  DOCUMENTS_CREATE: '/api/documents',
  DOCUMENTS_CREATE_LINK: '/api/documents/link',
  DOCUMENTS_LIST_BY_BOT: '/api/documents/allBy_botID',
  DOCUMENTS_DELETE: (docId) => `/api/documents/${docId}`,

  // Pricing
  PRICING_LIST: '/pricing',

  // Admin portal
  ADMIN_LOGIN: '/api/admin/login',
  ADMIN_STATS: '/api/admin/stats',
  ADMIN_USERS: '/api/admin/users',
  ADMIN_CREATE_USER: '/api/admin/users',
  ADMIN_AGENTS: '/api/admin/agents',
  ADMIN_CHATS: '/api/admin/chats',
  ADMIN_TURNKEY_REQUESTS: '/api/admin/turnkey-requests',
  ADMIN_PLANS: '/api/admin/plans',
  ADMIN_AGENT_TEMPLATE_PRICING: '/api/admin/agent-template-pricing',
  ADMIN_PROMO_CODES: '/api/admin/promo-codes',
  ADMIN_BAN_USER: (userId) => `/api/admin/users/${userId}/ban`,
  ADMIN_UNBAN_USER: (userId) => `/api/admin/users/${userId}/unban`,
  ADMIN_GIFT_SUBSCRIPTION: (userId) => `/api/admin/users/${userId}/gift-subscription`,
  ADMIN_FREE_AGENT_ACTIVATION: (userId) => `/api/admin/users/${userId}/free-agent-activation`,
  ADMIN_DELETE_PROMO_CODE: (promoCodeId) => `/api/admin/promo-codes/${promoCodeId}`,
  ADMIN_PARTNER_PAYOUTS: '/api/admin/partner-payouts',
  ADMIN_PARTNER_PAYOUT: (payoutId) => `/api/admin/partner-payouts/${payoutId}`,
  ADMIN_ERROR_REPORTS: '/api/admin/error-reports',
  ADMIN_LOGS: '/api/admin/logs',
  ADMIN_LOG: (logId) => `/api/admin/logs/${logId}`,
  ADMIN_LOG_RESOLVE: (logId) => `/api/admin/logs/${logId}/resolve`,
  ADMIN_EMAIL_BROADCAST: '/api/admin/email-broadcast',
  ADMIN_EMAIL_TARGETED_PREVIEW: '/api/admin/email-targeted-preview',
  ADMIN_EMAIL_TARGETED_BROADCAST: '/api/admin/email-targeted-broadcast',
  ADMIN_EMAIL_TARGETED_JOB: (jobId) => `/api/admin/email-targeted-broadcast/jobs/${jobId}`,
  TURNKEY_REQUESTS: '/api/payments/turnkey-requests',

  // Article Publisher
  ADMIN_AP_SETTINGS: '/api/admin/article-publisher/settings',
  ADMIN_AP_TOPICS: '/api/admin/article-publisher/topics',
  ADMIN_AP_TOPICS_GENERATE: '/api/admin/article-publisher/topics/generate',
  ADMIN_AP_TOPIC_DELETE: (id) => `/api/admin/article-publisher/topics/${id}`,
  ADMIN_AP_IMAGES: '/api/admin/article-publisher/images',
  ADMIN_AP_IMAGE_DELETE: (id) => `/api/admin/article-publisher/images/${id}`,
  ADMIN_AP_IMAGE_FILE: (id) => `/api/admin/article-publisher/images/${id}/file`,
  ADMIN_AP_JOBS: '/api/admin/article-publisher/jobs',
  ADMIN_AP_RUN_NOW: '/api/admin/article-publisher/run-now',
  ADMIN_AP_PREVIEW: '/api/admin/article-publisher/preview-article',

  ADMIN_SALES_TEAM: '/api/admin/sales/team-members',
  ADMIN_SALES_FUNNEL: '/api/admin/sales/funnel',
  ADMIN_SALES_TEAM_MEMBER: (id) => `/api/admin/sales/team-members/${id}`,
  ADMIN_SALES_EXCEL_UPLOAD: '/api/admin/sales/contacts/excel-upload',
  ADMIN_SALES_CONTACT_MANUAL: '/api/admin/sales/contacts/manual',
  ADMIN_SALES_CRM_CLEAR: '/api/admin/sales/contacts/clear',

  ADMIN_AI_MOP_DASHBOARD: '/api/admin/ai-mop/dashboard',
  ADMIN_AI_MOP_AGENTS: '/api/admin/ai-mop/agents',
  ADMIN_AI_MOP_AGENT_ASSIGN: (id) => `/api/admin/ai-mop/agents/${id}/assign`,
  ADMIN_AI_MOP_AGENT: (id) => `/api/admin/ai-mop/agents/${id}`,
  ADMIN_AI_MOP_LEADS: '/api/admin/ai-mop/leads',
  ADMIN_AI_MOP_LEADS_UPLOAD: '/api/admin/ai-mop/leads/excel-upload',
  ADMIN_AI_MOP_LEADS_CLEAR: '/api/admin/ai-mop/leads/clear',
  ADMIN_AI_MOP_ERRORS: '/api/admin/ai-mop/errors',
  ADMIN_AI_MOP_PIPELINE: '/api/admin/ai-mop/pipeline',
  ADMIN_AI_MOP_LEAD_RETRY_GENERATION: (id) => `/api/admin/ai-mop/leads/${id}/retry-generation`,
  ADMIN_AI_MOP_LEAD_RETRY_OUTREACH: (id) => `/api/admin/ai-mop/leads/${id}/retry-outreach`,
  ADMIN_AI_MOP_LEADS_RECOVER_LLM_BALANCE: '/api/admin/ai-mop/leads/recover-llm-balance-errors',

  SALES_LOGIN: '/api/sales/login',
  SALES_ME: '/api/sales/me',
  SALES_CONTACTS: '/api/sales/contacts',
  SALES_CONTACT: (id) => `/api/sales/contacts/${id}`,
  SALES_CONTACT_INVOICE: (id) => `/api/sales/contacts/${id}/invoice`,
  SALES_CONTACTS_REQUEST_MORE: '/api/sales/contacts/request-more',
  SALES_MGMT_TEAM: '/api/sales/management/team-members',
  SALES_MGMT_FUNNEL: '/api/sales/management/funnel',
  SALES_MGMT_TEAM_MEMBER: (id) => `/api/sales/management/team-members/${id}`,
  SALES_MGMT_EXCEL_UPLOAD: '/api/sales/management/contacts/excel-upload',
  SALES_MGMT_CRM_CLEAR: '/api/sales/management/contacts/clear',

  // Website Builder
  WEBSITES_LIST: '/api/v1/websites',
  WEBSITE_DETAIL: (id) => `/api/v1/websites/${id}`,
  WEBSITE_CREATE: '/api/v1/websites',
  WEBSITE_UPDATE: (id) => `/api/v1/websites/${id}`,
  WEBSITE_DELETE: (id) => `/api/v1/websites/${id}`,
  WEBSITE_PUBLISH: (id) => `/api/v1/websites/${id}/publish`,
  WEBSITE_UNPUBLISH: (id) => `/api/v1/websites/${id}/unpublish`,
  WEBSITE_GENERATE: (id) => `/api/v1/websites/${id}/generate`,
  WEBSITE_GENERATE_CREATE: '/api/v1/websites/generate/create-and-generate',
  WEBSITE_GENERATION_STATUS: (id) => `/api/v1/websites/${id}/generation-status`,
  WEBSITE_BLOCKS: (id) => `/api/v1/websites/${id}/blocks`,
  WEBSITE_BLOCK: (websiteId, blockId) => `/api/v1/websites/${websiteId}/blocks/${blockId}`,
  WEBSITE_BLOCKS_REORDER: (id) => `/api/v1/websites/${id}/blocks/reorder`,
  WEBSITE_BLOCK_DUPLICATE: (websiteId, blockId) => `/api/v1/websites/${websiteId}/blocks/${blockId}/duplicate`,
  WEBSITE_BLOCK_EDIT_PROMPT: (websiteId, blockId) =>
    `/api/v1/websites/${websiteId}/blocks/${blockId}/edit-prompt`,
  WEBSITE_BLOCK_EDIT_PROMPT_TASK: (websiteId, taskId) =>
    `/api/v1/websites/${websiteId}/edit-prompt/tasks/${taskId}`,
  WEBSITE_DOMAINS: (id) => `/api/v1/websites/${id}/domains`,
  WEBSITE_DOMAIN: (websiteId, domainId) => `/api/v1/websites/${websiteId}/domains/${domainId}`,
  WEBSITE_DOMAIN_VERIFY: (websiteId, domainId) => `/api/v1/websites/${websiteId}/domains/${domainId}/verify`,
  WEBSITE_SCHEMA: (id) => `/api/v1/websites/${id}/schema`,
  WEBSITE_SCHEMA_BY_SLUG: (slug) => `/api/v1/websites/by-slug/${slug}/schema`,
  WEBSITE_SCHEMA_BY_DOMAIN: (domain) => `/api/v1/websites/by-domain/${domain}/schema`,
  WEBSITE_PUBLIC_SCHEMA: '/public-website/schema',
  WEBSITE_TEMPLATES: '/api/v1/websites/templates',
  WEBSITE_META_UPDATE: (id) => `/api/v1/websites/${id}/meta`,
  WEBSITE_SEO_META: (id) => `/api/v1/websites/${id}/seo/meta`,
  WEBSITE_SEO_PREVIEW: (id) => `/api/v1/websites/${id}/seo/preview`,
  WEBSITE_FAVICON_UPLOAD: (id) => `/api/v1/websites/${id}/favicon`,
  WEBSITE_OG_IMAGE_UPLOAD: (id) => `/api/v1/websites/${id}/og-image/upload`,
  WEBSITE_OG_IMAGE_GENERATE: (id) => `/api/v1/websites/${id}/og-image/generate`,
  AGENT_PUBLIC_DATA: (id) => `/api/v1/agents/${id}/public-data`,
  AGENT_BOOKING_SLOTS: (id) => `/api/v1/agents/${id}/booking/slots`,
  AGENT_BOOKING_APPOINTMENTS: (id) => `/api/v1/agents/${id}/booking/appointments`,

  // Projects (Portal)
  PROJECTS_LIST: '/api/projects',
  PROJECT_DETAIL: (id) => `/api/projects/${id}`,
  PROJECT_CREATE: '/api/projects',
  PROJECT_UPDATE: (id) => `/api/projects/${id}`,
  PROJECT_ARCHIVE: (id) => `/api/projects/${id}`,
  PROJECT_AI_GENERATE_PLAN: '/api/projects/ai/generate-plan',
  PROJECT_AI_APPLY_PLAN: '/api/projects/ai/apply-plan',
  PROJECT_DASHBOARD: (id) => `/api/projects/${id}/dashboard`,
  // Project Documents (Knowledge Base)
  PROJECT_DOCUMENTS: (projectId) => `/api/projects/${projectId}/documents`,
  PROJECT_DOCUMENTS_LINK: (projectId) => `/api/projects/${projectId}/documents/link`,
  PROJECT_DOCUMENT: (projectId, docId) => `/api/projects/${projectId}/documents/${docId}`,
  PROJECT_DOCUMENT_REINDEX: (projectId, docId) => `/api/projects/${projectId}/documents/${docId}/reindex`,
  // Project Related Agents
  PROJECT_AGENTS: (projectId) => `/api/agents/allBy_tgID?project_id=${projectId}`,
  // Project Website
  PROJECT_WEBSITE: (projectId) => `/api/projects/${projectId}/website`,
  // Project CRM
  PROJECT_CRM: (projectId) => `/api/projects/${projectId}/crm/summary`,
  // Project Content
  PROJECT_CONTENT_DATA: (projectId) => `/api/projects/${projectId}/content`,
  // Project AI Manager
  PROJECT_AI_MANAGER: (projectId) => `/api/projects/${projectId}/ai-manager`,
  PROJECT_AI_MANAGER_CHAT: (projectId) => `/api/projects/${projectId}/ai-manager/chat`,
  // Project Checklist visibility
  PROJECT_CHECKLIST_VISIBILITY: (projectId) => `/api/projects/${projectId}/checklist-visibility`,
  // Project Websites
  PROJECT_WEBSITES: (projectId) => `/api/projects/${projectId}/websites`,
  PROJECT_CREATE_WEBSITE: (projectId) => `/api/projects/${projectId}/websites`,
  // Project Integrations
  PROJECT_INTEGRATIONS: (projectId) => `/api/projects/${projectId}/integrations`,
  PROJECT_INTEGRATION: (projectId, integrationId) => `/api/projects/${projectId}/integrations/${integrationId}`,
  PROJECT_INTEGRATION_ROTATE_TOKEN: (projectId, integrationId) =>
    `/api/projects/${projectId}/integrations/${integrationId}/rotate-token`,
  PROJECT_INTEGRATION_WEBHOOK: (projectId, token) => `/api/projects/${projectId}/integrations/webhook/${token}`,

  // Custom agents subsystem
  CUSTOM_LOGIN: '/api/custom/login',
  CUSTOM_ADMIN_LOGIN: '/api/custom/admin/login',
  CUSTOM_ADMIN_DASHBOARD: '/api/custom/admin/dashboard',
  CUSTOM_ADMIN_AUTOMATIONS: '/api/custom/admin/automations',
  CUSTOM_ADMIN_AUTOMATION: (id) => `/api/custom/admin/automations/${id}`,
  CUSTOM_ADMIN_AUTOMATION_CREDENTIALS: (id) => `/api/custom/admin/automations/${id}/credentials`,
  CUSTOM_AUTOMATION_DASHBOARD: (id) => `/api/custom/automations/${id}/dashboard`,
  CUSTOM_AUTOMATION_ACTIVITY: (id) => `/api/custom/automations/${id}/activity`,
  CUSTOM_AUTOMATION_ACCOUNTS: (id) => `/api/custom/automations/${id}/accounts`,
  CUSTOM_AUTOMATION_ACCOUNTS_BAN_STATS: (id) => `/api/custom/automations/${id}/accounts/ban-stats`,
  CUSTOM_AUTOMATION_ACCOUNTS_HEALTH_CHECK: (id) => `/api/custom/automations/${id}/accounts/health-check`,
  CUSTOM_AUTOMATION_ACCOUNT_SPAMBLOCK_CHECK: (id, accountId) =>
    `/api/custom/automations/${id}/accounts/${accountId}/spamblock-check`,
  CUSTOM_AUTOMATION_ACCOUNTS_SETUP_TEMPLATES: (id) => `/api/custom/automations/${id}/accounts/setup-templates`,
  CUSTOM_AUTOMATION_ACCOUNTS_PREPARE: (id) => `/api/custom/automations/${id}/accounts/prepare`,
  CUSTOM_AUTOMATION_ACCOUNTS_PREPARE_STATUS: (id) => `/api/custom/automations/${id}/accounts/prepare-status`,
  CUSTOM_AUTOMATION_ACCOUNTS_WARMUP_START: (id) => `/api/custom/automations/${id}/accounts/warmup/start`,
  CUSTOM_AUTOMATION_ACCOUNTS_QR_START: (id) => `/api/custom/automations/${id}/accounts/qr/start`,
  CUSTOM_AUTOMATION_ACCOUNTS_QR_STATUS: (id) => `/api/custom/automations/${id}/accounts/qr/status`,
  CUSTOM_AUTOMATION_ACCOUNTS_QR_2FA: (id) => `/api/custom/automations/${id}/accounts/qr/verify_2fa`,
  CUSTOM_AUTOMATION_ACCOUNTS_SMS_REQUEST: (id) => `/api/custom/automations/${id}/accounts/sms/request`,
  CUSTOM_AUTOMATION_ACCOUNTS_SMS_VERIFY: (id) => `/api/custom/automations/${id}/accounts/sms/verify`,
  CUSTOM_AUTOMATION_SETTINGS: (id) => `/api/custom/automations/${id}/settings`,
  CUSTOM_AUTOMATION_CHATS: (id) => `/api/custom/automations/${id}/chats`,
  CUSTOM_AUTOMATION_CHAT: (id, chatId) => `/api/custom/automations/${id}/chats/${chatId}`,
  CUSTOM_AUTOMATION_CHAT_MESSAGES: (id, chatId) => `/api/custom/automations/${id}/chats/${chatId}/messages`,
  CUSTOM_AUTOMATION_CHAT_IMPORT: (id) => `/api/custom/automations/${id}/chats/bulk-import`,
  CUSTOM_AUTOMATION_CHAT_IMPORT_JOBS: (id) => `/api/custom/automations/${id}/chats/import-jobs`,
  CUSTOM_AUTOMATION_CHAT_INSPECT_COMMENTS: (id) => `/api/custom/automations/${id}/chats/inspect-comments`,
  CUSTOM_AUTOMATION_CHAT_INSPECT_STATUS: (id) => `/api/custom/automations/${id}/chats/inspect-status`,
  CUSTOM_AUTOMATION_CHAT_DISCOVERY: (id) => `/api/custom/automations/${id}/chats/discovery`,
  CUSTOM_AUTOMATION_CHAT_DISCOVERY_APPROVE: (id, taskId) => `/api/custom/automations/${id}/chats/discovery/${taskId}/approve`,
  CUSTOM_AUTOMATION_CHAT_DISCOVERY_REJECT: (id, taskId) => `/api/custom/automations/${id}/chats/discovery/${taskId}/reject`,
  CUSTOM_AUTOMATION_CHAT_JOIN: (id) => `/api/custom/automations/${id}/chats/join`,
  CUSTOM_AUTOMATION_CHAT_MONITOR: (id) => `/api/custom/automations/${id}/chats/monitor`,
  CUSTOM_AUTOMATION_LEADS: (id) => `/api/custom/automations/${id}/leads`,
  CUSTOM_AUTOMATION_LEAD: (id, leadId) => `/api/custom/automations/${id}/leads/${leadId}`,
  CUSTOM_AUTOMATION_LEAD_MESSAGES: (id, leadId) => `/api/custom/automations/${id}/leads/${leadId}/messages`,
  CUSTOM_AUTOMATION_LEAD_STATUS: (id, leadId) => `/api/custom/automations/${id}/leads/${leadId}/status`,
  CUSTOM_AUTOMATION_LEAD_TRANSFER: (id, leadId) => `/api/custom/automations/${id}/leads/${leadId}/transfer`,
  CUSTOM_AUTOMATION_DMP_IMPORTS: (id) => `/api/custom/automations/${id}/dmp/imports`,
  CUSTOM_AUTOMATION_DMP_ORDERS: (id) => `/api/custom/automations/${id}/dmp/orders`,
  CUSTOM_AUTOMATION_DMP_POLL: (id) => `/api/custom/automations/${id}/dmp/poll`,
  CUSTOM_AUTOMATION_AMOCRM_CONNECTION: (id) => `/api/custom/automations/${id}/amocrm/connection`,
  CUSTOM_AUTOMATION_AMOCRM_CREDENTIALS: (id) => `/api/custom/automations/${id}/amocrm/credentials`,
  CUSTOM_AUTOMATION_AMOCRM_OAUTH_START: (id) => `/api/custom/automations/${id}/amocrm/oauth/start`,
  CUSTOM_AUTOMATION_AMOCRM_SYNC: (id) => `/api/custom/automations/${id}/amocrm/sync`,
  CUSTOM_AUTOMATION_DMP_WEBHOOK_ROTATE: (id) => `/api/custom/automations/${id}/dmp/webhook-secret/rotate`,
  CUSTOM_AUTOMATION_TELEGRAM_BOT: (id) => `/api/custom/automations/${id}/telegram-bot`,
  CUSTOM_AUTOMATION_GOOGLE_SHEETS: (id) => `/api/custom/automations/${id}/google-sheets`,
  CUSTOM_AUTOMATION_PROMPTS: (id) => `/api/custom/automations/${id}/prompts`,
  CUSTOM_AUTOMATION_PROMPT: (id, promptId) => `/api/custom/automations/${id}/prompts/${promptId}`,
  CUSTOM_AUTOMATION_PROMPT_TOGGLE: (id, promptId) => `/api/custom/automations/${id}/prompts/${promptId}/toggle`,
  CUSTOM_AUTOMATION_PROMPT_TEST: (id, promptId) => `/api/custom/automations/${id}/prompts/${promptId}/test`,
  CUSTOM_AUTOMATION_CHAT_NEUROCOMMENTING_CONFIG: (id, chatId) =>
    `/api/custom/automations/${id}/chats/${chatId}/neurocommenting-config`,
  CUSTOM_AUTOMATION_CHAT_NEUROCOMMENTING_RUN: (id) => `/api/custom/automations/${id}/chats/neurocommenting`,
  CUSTOM_AUTOMATION_CHAT_DISCUSSION_CONFIG: (id, chatId) =>
    `/api/custom/automations/${id}/chats/${chatId}/discussion-config`,
  CUSTOM_AUTOMATION_CHAT_DISCUSSION_RUN: (id) => `/api/custom/automations/${id}/chats/discussion`,
  CUSTOM_AUTOMATION_CHAT_SHILLING_CONFIG: (id, chatId) =>
    `/api/custom/automations/${id}/chats/${chatId}/shilling-config`,
  CUSTOM_AUTOMATION_CHAT_SHILLING_RUN: (id) => `/api/custom/automations/${id}/chats/shilling`,
  CUSTOM_AUTOMATION_TEST: (id) => `/api/custom/automations/${id}/test`,
  CUSTOM_AUTOMATION_TEST_JOIN: (id) => `/api/custom/automations/${id}/test/join`,
  CUSTOM_AUTOMATION_TEST_SHILLING: (id) => `/api/custom/automations/${id}/test/shilling`,
  CUSTOM_AUTOMATION_TEST_NEUROCOMMENTING: (id) => `/api/custom/automations/${id}/test/neurocommenting`,
  CUSTOM_AUTOMATION_TEST_CHANNEL_ACTIVITY: (id) => `/api/custom/automations/${id}/test/channel-activity`,
  CUSTOM_AUTOMATION_TEST_DMP: (id) => `/api/custom/automations/${id}/test/dmp`,
};

export const AGENT_ROLES = {
  SALES_MANAGER: 'sales_manager',
  SUPPORT: 'support',
  ASSISTANT: 'assistant',
};

export const AGENT_TASKS = {
  SALES: 'sales',
  FAQ: 'faq',
  CONTACTS: 'contacts',
};

// Pricing plans are served by backend (/api/payments/plans) to keep bot + web consistent.
export const PRICING_PLANS = [];

export const NAVIGATION_ROUTES = {
  HOME: '/',
  AUTH: '/auth',
  AGENTS: '/agents',
  AGENT_ANALYTICS: (id) => `/agents/${id}/analytics`,
  CREATE_AGENT: '/create-agent',
  CREATE_AGENT_AI: '/create-agent-ai',
  DOCUMENTATION: '/documentation',
  EDIT_AGENT: (id) => `/agents/${id}/edit`,
  PRICING: '/pricing',
  PARTNER: '/partner',
  MANAGEMENT_PORTAL: '/management-portal',
  PUBLIC_OFFER: '/public-offer',
  USER_AGREEMENT: '/user-agreement',
  PRIVACY_POLICY: '/privacy',
  // Website Builder
  WEBSITE_PREVIEW: (id) => `/preview/${id}`,
  WEBSITE_PUBLIC: (slug) => `/w/${slug}`,
  WEBSITE_EDITOR: (id) => `/websites/${id}/edit`,
  WEBSITES_LIST: '/websites',
  WEBSITE_CREATE: '/websites/create',
  // Projects (Portal)
  PROJECTS_LIST: '/projects',
  PROJECT_CREATE: '/projects/create',
  PROJECT_DETAIL: (id) => `/projects/${id}`,
  PROJECT_AGENTS: (id) => `/projects/${id}/agents`,
  PROJECT_KNOWLEDGE: (id) => `/projects/${id}/knowledge`,
  PROJECT_CRM: (id) => `/projects/${id}/crm`,
  PROJECT_WEBSITE: (id) => `/projects/${id}/website`,
  PROJECT_CONTENT: (id) => `/projects/${id}/content`,
  PROJECT_MANAGER: (id) => `/projects/${id}/manager`,
  PROJECT_SETTINGS: (id) => `/projects/${id}/settings`,
  PROJECT_INTEGRATIONS: (id) => `/projects/${id}/integrations`,

  // Custom agents subsystem
  CUSTOM_LOGIN: '/custom/login',
  CUSTOM_ADMIN: '/custom/admin',
  CUSTOM_ADMIN_DASHBOARD: '/custom/admin',
  CUSTOM_ADMIN_NEW: '/custom/admin/new',
  CUSTOM_ADMIN_AUTOMATIONS: '/custom/admin',
  CUSTOM_ADMIN_AUTOMATION_EDIT: (id) => `/custom/automations/${id}/settings`,
  CUSTOM_ADMIN_AUTOMATION_ACCESS: (id) => `/custom/automations/${id}/settings`,
  CUSTOM_AUTOMATION_DASHBOARD: (id) => `/custom/automations/${id}/dashboard`,
  CUSTOM_AUTOMATION_ACTIVITY: (id) => `/custom/automations/${id}/activity`,
  CUSTOM_AUTOMATION_ACCOUNTS: (id) => `/custom/automations/${id}/accounts`,
  CUSTOM_AUTOMATION_SETTINGS: (id) => `/custom/automations/${id}/settings`,
  CUSTOM_AUTOMATION_CHATS: (id) => `/custom/automations/${id}/chats`,
  CUSTOM_AUTOMATION_CHAT_DISCOVERY: (id) => `/custom/automations/${id}/chats/discovery`,
  CUSTOM_AUTOMATION_LEADS: (id) => `/custom/automations/${id}/leads`,
  CUSTOM_AUTOMATION_LEAD_CHAT: (id, leadId) => `/custom/automations/${id}/leads/${leadId}/chat`,
  CUSTOM_AUTOMATION_DMP: (id) => `/custom/automations/${id}/dmp`,
  CUSTOM_AUTOMATION_AMOCRM: (id) => `/custom/automations/${id}/amocrm`,
  CUSTOM_AUTOMATION_PROMPTS: (id) => `/custom/automations/${id}/prompts`,
  CUSTOM_AUTOMATION_PROMPT_EDIT: (id, promptId) => `/custom/automations/${id}/prompts/${promptId}/edit`,
  CUSTOM_AUTOMATION_TEST: (id) => `/custom/automations/${id}/test`,
};

// User-facing messages; backend detail (FastAPI) is preferred when present (see errorUtils).
export const ERROR_MESSAGES = {
  NETWORK_ERROR: 'Ошибка подключения. Проверьте интернет соединение.',
  UNAUTHORIZED: 'Пожалуйста, войдите в систему.',
  FORBIDDEN: 'У вас нет доступа к этому ресурсу.',
  NOT_FOUND: 'Ресурс не найден.',
  CONFLICT: 'Пользователь уже существует.',
  SERVER_ERROR: 'Ошибка сервера. Попробуйте позже.',
  VALIDATION_ERROR: 'Пожалуйста, проверьте корректность данных.',
};

export const SUCCESS_MESSAGES = {
  AGENT_CREATED: 'Агент успешно создан!',
  AGENT_UPDATED: 'Агент успешно обновлен!',
  AGENT_DELETED: 'Агент успешно удален!',
  LOGIN_SUCCESS: 'Успешный вход в систему!',
  LOGOUT_SUCCESS: 'Вы успешно вышли из системы.',
};

export const VALIDATION = {
  EMAIL_PATTERN: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  // Auth: must match backend Pydantic (router_users/schemas.py)
  USERNAME_MIN_LENGTH: 3,
  USERNAME_MAX_LENGTH_LOGIN: 255,   // LoginUser.name (username or email)
  USERNAME_MAX_LENGTH_REGISTER: 32, // NewUser.name
  PASSWORD_MIN_LENGTH: 6,          // both schemas
  PASSWORD_MAX_LENGTH: 30,          // both schemas
  EMAIL_CODE_LENGTH: 6,
  EMAIL_RESEND_COOLDOWN_SECONDS: 120,
  AGENT_NAME_MIN_LENGTH: 2,
  AGENT_NAME_MAX_LENGTH: 50,
  FILE_MAX_SIZE: 10 * 1024 * 1024, // 10MB
  ALLOWED_FILE_EXTENSIONS: ['pdf', 'docx', 'doc', 'txt', 'md'],
};

export const DEBOUNCE_DELAY = {
  SEARCH: 300,
  RESIZE: 300,
  SCROLL: 300,
};

export default {
  HTTP_STATUS,
  API_ROUTES,
  AGENT_ROLES,
  AGENT_TASKS,
  PRICING_PLANS,
  NAVIGATION_ROUTES,
  ERROR_MESSAGES,
  SUCCESS_MESSAGES,
  VALIDATION,
  DEBOUNCE_DELAY,
};
